; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27812.2 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\root\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
